version: '3.8'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    restart: always

  app:
    build: .
    ports:
      - "80:80"
    environment:
      PORT: 80
      DATABASE_URL: postgres://postgres:root@db:5432/postgres
    depends_on:
      - db
    restart: always

volumes:
  postgres_data: